"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMLogon.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMDataServer.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMComponents.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMCalendar.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMTunes.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMMessenger.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMSecurity.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMOn2.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMSoc.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMSica.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMPyme.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMPymePos.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMSigueConta.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMSigueComunes.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMFacturasElectronicas.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMPacs.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMSgp.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMSec.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/JAMUsersRoots/mi360/JAMSrh.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/activation.jar  
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/ant-1.5.1.jar             
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/axis.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/axis-ant.jar             
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/commons-codec-1.3.jar             
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/commons-collections.jar   
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/commons-digester.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/commons-discovery.jar     
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/commons-el.jar            
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/commons-httpclient-3.0.1.jar   
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/commons-logging.jar       
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/inieditor.jar                        
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/jaxrpc.jar       
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/mail.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/soap.jar       
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/wsdl4j-1.5.1.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/xercesImpl.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/not-yet-commons-ssl-0.3.11.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/PDFBox-0.7.3.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/fontbox-0.1.0.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/jxl.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/RXTXcomm.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/SMSGatewayFull142.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/core.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/javase.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/jcommon-1.0.17.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/jfreechart-1.0.14.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/dpfpenrollment.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/dpfpverification.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/dpotapi.jar
"C:/Program Files (x86)/GnuWin32/bin/wget" http://www.officenet2.info/JAMMexico/dpotjni.jar